package guard

import (
	"strings"
)

const codexHeader = `# gh board guard rules for Codex CLI (execpolicy), the second layer under
# the PreToolUse hook because a hook failure does not block in Codex.
# Generated by gh board agent install --agent codex from the kit's embedded
# patterns: one prefix_rule per spelling whose only star is the trailing one,
# in patterns.json order; the shells Codex runs commands with are never
# forbidden here, the hook covers them. Do not edit; run the installer
# again to update.
# Prefix rules cannot express methods after a path, arbitrary option order,
# GraphQL bodies, absolute paths, shell scripts, or case-insensitive programs.
# Generated spellings include gh.exe and all method case combinations when
# the method precedes the path. Other program casing and shell forms require
# the kit's guard check hook. Subcommands remain case sensitive.
`

// CodexRules returns the execpolicy rules file of Codex: one forbidden
// prefix_rule per rule that is a plain subcommand prefix (a single
// trailing " *"), one per line in rule order, with the strict prefixes
// when strict. The file is the golden content of agents/codex/gh-board.rules.
func CodexRules(strict bool) ([]byte, error) {
	rules, err := Rules(strict)
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString(codexHeader)
	b.WriteString("# Strict mode: ")
	if strict {
		b.WriteString("on\n")
	} else {
		b.WriteString("off\n")
	}
	for _, r := range expandedRules(rules) {
		if tokens, ok := CodexPrefix(r); ok {
			writePrefixRule(&b, tokens)
		}
	}
	return []byte(b.String()), nil
}

// CodexPrefix is PrefixTokens without the rules on the shells themselves
// (sh -c, bash -lc and the others of the strict set): execpolicy sees the
// argv Codex runs, which always starts with its own shell wrapper, so such
// a rule would forbid every command. Those rules live in the hook only.
func CodexPrefix(rule string) ([]string, bool) {
	tokens, ok := PrefixTokens(rule)
	if !ok || shellPrograms[programBase(tokens[0])] {
		return nil, false
	}
	return tokens, true
}

// PrefixTokens returns the argv prefix of a rule whose only wildcard is a
// trailing " *", which is the only shape an execpolicy prefix_rule can
// express exactly.
func PrefixTokens(rule string) ([]string, bool) {
	if strings.Count(rule, "*") != 1 || !strings.HasSuffix(rule, " *") {
		return nil, false
	}
	tokens := strings.Fields(strings.TrimSuffix(rule, " *"))
	if len(tokens) == 0 {
		return nil, false
	}
	return tokens, true
}

// writePrefixRule writes one single-line rule; the justification names the
// words so that Codex shows which family refused the command.
func writePrefixRule(b *strings.Builder, tokens []string) {
	b.WriteString("prefix_rule(pattern=[")
	for i, t := range tokens {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(starlarkString(t))
	}
	b.WriteString("], decision=\"forbidden\", justification=")
	b.WriteString(starlarkString("gh board guard denies " + strings.Join(tokens, " ")))
	b.WriteString(")\n")
}

func starlarkString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
