package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

var (
	emDash = string(rune(0x2014))
	enDash = string(rune(0x2013))
)

func TestDashViolations(t *testing.T) {
	data := []byte("clean\nwith " + emDash + " em\nwith " + enDash + " en\n")
	got := dashViolations("docs/a.md", data)
	if len(got) != 2 || got[0] != "docs/a.md:2: em dash" || got[1] != "docs/a.md:3: en dash" {
		t.Fatalf("got %v", got)
	}
	if len(dashViolations("x", []byte("plain - hyphen"))) != 0 {
		t.Fatal("hyphens are allowed")
	}
}

func longFunc(lines int) string {
	var b strings.Builder
	b.WriteString("package p\n\nfunc long() {\n")
	for i := 0; i < lines-2; i++ {
		b.WriteString("\t_ = 1\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func TestLengthViolations(t *testing.T) {
	short := []byte("package p\n\nfunc ok() {}\n\nfunc none()\n")
	if got := lengthViolations("a.go", short); len(got) != 0 {
		t.Fatalf("short file flagged: %v", got)
	}
	if got := lengthViolations("b.go", []byte(longFunc(41))); len(got) != 1 || !strings.Contains(got[0], "function long is 41 lines") {
		t.Fatalf("41-line function: %v", got)
	}
	if got := lengthViolations("c.go", []byte(longFunc(40))); len(got) != 0 {
		t.Fatalf("40-line function flagged: %v", got)
	}
	big := "package p\n" + strings.Repeat("// c\n", 300)
	if got := lengthViolations("d.go", []byte(big)); len(got) != 1 || !strings.Contains(got[0], "301 lines") {
		t.Fatalf("301-line file: %v", got)
	}
	if got := lengthViolations("e.go", []byte("package p\n\nfunc {")); len(got) != 1 || !strings.Contains(got[0], "parse error") {
		t.Fatalf("parse error: %v", got)
	}
	if countLines([]byte("")) != 0 || countLines([]byte("a")) != 1 || countLines([]byte("a\nb\n")) != 2 {
		t.Fatal("countLines is wrong")
	}
}

func TestHelpers(t *testing.T) {
	if !isGenerated([]byte("// Code generated by x. DO NOT EDIT.\npackage p\n")) || isGenerated([]byte("package p")) {
		t.Fatal("isGenerated is wrong")
	}
	if !isBinary([]byte("ab\x00c")) || isBinary([]byte("text")) {
		t.Fatal("isBinary is wrong")
	}
	if shortHash(" abcdef0123456789 ") != "abcdef012345" || shortHash("abc") != "abc" {
		t.Fatal("shortHash is wrong")
	}
}

func TestCommitViolations(t *testing.T) {
	log := "aaaaaaaaaaaaaaaa\x1ffeat: add laws\n\nCo-Authored-By: Bot <bot@example.com>\n\x1e" +
		"bbbbbbbbbbbbbbbb\x1ffix: clean\n\x1e" +
		"cccccccccccccccc\x1fdocs: deck\n\nGenerated with Tool\n\x1e"
	got := commitViolations(log)
	if len(got) != 2 || !strings.Contains(got[0], "aaaaaaaaaaaa") || !strings.Contains(got[1], "generated with") {
		t.Fatalf("got %v", got)
	}
}

func writeFixture(t *testing.T, root, rel, content string) {
	t.Helper()
	path := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestRunOnFixture(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "README.md", "clean text\n")
	writeFixture(t, root, "docs/bad.md", "title "+emDash+" subtitle\n")
	writeFixture(t, root, "pkg/long.go", longFunc(45))
	writeFixture(t, root, "pkg/gen.go", "// Code generated by x. DO NOT EDIT.\n"+longFunc(45))
	writeFixture(t, root, "vendor/skip.md", emDash+"\n")
	writeFixture(t, root, "bin.dat", "a\x00"+emDash)
	got, err := run(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 2 || got[0] != "docs/bad.md:1: em dash" || !strings.HasPrefix(got[1], "pkg/long.go:3: function long is 45 lines") {
		t.Fatalf("got %v", got)
	}
	if _, err := run(filepath.Join(root, "missing")); err == nil {
		t.Fatal("a missing root must fail")
	}
}

func git(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", append([]string{"-c", "commit.gpgsign=false"}, args...)...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v: %s", args, err, out)
	}
}

func TestCheckCommits(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not installed")
	}
	root := t.TempDir()
	if got, err := checkCommits(root); err != nil || len(got) != 0 {
		t.Fatalf("no repository: %v, %v", got, err)
	}
	git(t, root, "init", "-q", "-b", "main")
	git(t, root, "config", "user.email", "t@example.com")
	git(t, root, "config", "user.name", "t")
	if got, err := checkCommits(root); err != nil || len(got) != 0 {
		t.Fatalf("unborn branch: %v, %v", got, err)
	}
	writeFixture(t, root, "a.txt", "a\n")
	git(t, root, "add", "a.txt")
	git(t, root, "commit", "-q", "-m", "feat: first\n\nCo-Authored-By: Bot <bot@example.com>")
	got, err := checkCommits(root)
	if err != nil || len(got) != 1 || !strings.Contains(got[0], "co-authored-by") {
		t.Fatalf("trailer: %v, %v", got, err)
	}
}

func TestExecute(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "ok.md", "clean\n")
	var out, errOut strings.Builder
	if code := execute([]string{"-root", root}, &out, &errOut); code != 0 || !strings.Contains(out.String(), "laws: ok") {
		t.Fatalf("clean: code %d, out %q", code, out.String())
	}
	writeFixture(t, root, "bad.md", emDash+"\n")
	out.Reset()
	if code := execute([]string{"-root", root}, &out, &errOut); code != 1 || !strings.Contains(out.String(), "bad.md:1: em dash") {
		t.Fatalf("violations: code %d, out %q", code, out.String())
	}
	if code := execute([]string{"-root", filepath.Join(root, "missing")}, &out, &errOut); code != 2 {
		t.Fatalf("missing root: code %d", code)
	}
	if code := execute([]string{"-bogus"}, &out, &errOut); code != 2 {
		t.Fatalf("bad flag: code %d", code)
	}
}

func TestWalkSkipsIgnoredFiles(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, ".gitignore", "# build outputs\n/bin\n*.tmp\ncache/\n!keep.tmp\n\n")
	writeFixture(t, root, "kept.md", "a\n")
	writeFixture(t, root, "bin", "ignored root file\n")
	writeFixture(t, root, "src/bin", "not anchored here\n")
	writeFixture(t, root, "src/scratch.tmp", "ignored anywhere\n")
	writeFixture(t, root, "src/cache/x.md", "ignored directory\n")
	writeFixture(t, root, "gen/.gitignore", "*\n")
	writeFixture(t, root, "gen/types.d.ts", "ignored by the nested file\n")
	writeFixture(t, root, "gen/deep/more.ts", "ignored by the nested file\n")
	writeFixture(t, root, "other/after.md", "walked after the nested file\n")
	var seen []string
	err := walkFiles(root, func(_, rel string) error {
		seen = append(seen, rel)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	// A nested "*" hides its own .gitignore too, as git does.
	want := ".gitignore,kept.md,other/after.md,src/bin"
	if got := strings.Join(seen, ","); got != want {
		t.Fatalf("walked %s, want %s", got, want)
	}
}

func TestIgnorePatterns(t *testing.T) {
	if _, ok := parseIgnoreLine("  "); ok {
		t.Fatal("blank lines carry no pattern")
	}
	if _, ok := parseIgnoreLine("/"); ok {
		t.Fatal("a bare slash carries no pattern")
	}
	p, ok := parseIgnoreLine("docs/*.md\r")
	if !ok || !p.anchored || p.dirOnly || !p.matches("docs/a.md") || p.matches("x/docs/a.md") {
		t.Fatalf("pattern with a slash = %+v, %v", p, ok)
	}
	rules := ignoreRules{dir: "/r", patterns: []ignorePattern{{text: "build", dirOnly: true}}}
	if rules.matches("build", false) || !rules.matches("a/build", true) {
		t.Fatal("directory-only patterns match directories at any depth")
	}
	var stack ignoreStack
	if stack.ignored("/r", "a", false) {
		t.Fatal("an empty stack ignores nothing")
	}
}
